name: "Continuous integration"

on:
  push:
    branches:
      - "master"
      - "develop"
    tags:
       - "*"
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - {php-version: "7.4"}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          tools: "composer, cs2pr"
      - name: "Get Composer cache directory"
        id: "composer-cache"
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: "Restore dependencies cache"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ github.job }}-${{ matrix.php-version }}-dependencies-${{ hashFiles('**/composer.lock') }}"
      - name: "Install Composer dependencies"
        run: |
          composer install --ansi --no-interaction --no-progress --prefer-dist
      - name: "PHP Parallel Lint"
        run: |
          vendor/bin/parallel-lint --colors --checkstyle --exclude ./vendor/ . | cs2pr
      - name: "PHP_CodeSniffer"
        run: |
          vendor/bin/phpcs -q --report=checkstyle | cs2pr
      - name: "Check for missing/outdated headers"
        run: |
          vendor/bin/licence-headers-check --ansi --no-interaction
